version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017
      CACHE_URL: redis://cache:6379
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - app-network

volumes:
  mongo_data:
  cache:

networks:
  app-network:
    driver: bridge
