version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
